FROM greyltc/archlinux-aur:yay
RUN useradd -m builder
RUN pacman -Sy --needed --noconfirm sudo git base-devel archlinux-keyring
RUN echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/01_builder
RUN pacman -Suy --noconfirm
RUN sudo -u builder yay -Sy --needed --noconfirm nmap emacs-nox rsync tmux gnu-netcat ldns bind traceroute iperf3 vault nfs-utils cifs-utils openssh mariadb-clients

CMD ["/bin/bash"]
